### PR TITLE
Add camera intent handling

### PR DESCRIPTION
**Pull request by divy4**
Adds camera support for the CreateMeetupPhoto page.

### CODE REVIEW

**Comment by schmidtwmark** [comment]
What can we do about the black screen on Take Photo page? Maybe make a larger camera button? Is it too challenging to make the black rectangle in the viewfinder?  [This](https://developer.android.com/training/camera/cameradirect) seems to have everything we'd need to make that happen, and I think the UI would benefit a lot from not having to drop into a different application (the user could still see our text telling them what to do at the top)

This is fine for now, so I'll approve it, but we should really consider making those changes.

**Comment by schmidtwmark** [comment]
Also, we should probably merge develop into this branch first and update the classes in CreateMeetupActivity's list/fix any other non-automatic merge things

**Comment by divy4** [comment]
> What can we do about the black screen on Take Photo page? Maybe make a larger camera button? Is it too challenging to make the black rectangle in the viewfinder? [This](https://developer.android.com/training/camera/cameradirect) seems to have everything we'd need to make that happen, and I think the UI would benefit a lot from not having to drop into a different application (the user could still see our text telling them what to do at the top)
> 
> This is fine for now, so I'll approve it, but we should really consider making those changes.

That sounds good. But how about for now we try to get everything functional and improve it once we're done? 

> Also, we should probably merge develop into this branch first and update the classes in CreateMeetupActivity's list/fix any other non-automatic merge things

Wait, do you mean rebase this branch onto develop? I'm not sure why we would want to merge develop into this branch. And what problems would we have with CreateMeetupActivity's list? The camera intent is separate from the sequence and returns once a picture is accepted.

**Comment by schmidtwmark** [comment]
Of course, I just meant in the future it's something we should keep in mind. And sure, maybe I mean, rebase, I'm not sure about the git thing. But if we do git merge develop while on this branch, we'll get all the changes from develop. These changes include the select dogs page, which changed CreateMeetupActivity's list. Even though it's not a merge conflict, I don't think auto-merging this into develop will resolve it correctly.

**Comment by divy4** [comment]
Ok, that sounds great! Ah, but we can get those changes with rebase too. (If you already understand this, you can ignore the rest of this) In the example you gave, merge takes the commits from develop that this branch doesn't have and makes them part of this branch's history (after branching from develop), whereas rebase detaches the point this branch was made from develop and reattaches it to the head of develop. So overall, merge results in this branch having more commits than what it did before, which can get mixed up with the original commits where rebase results in no commits being added to this branch, and yet it will contain the changes it didn't have before.

**Pull request merged**
