### PR TITLE
Meetup in progress feedback from TA

### PR DESCRIPTION
**Pull request by nicknytko**
photo_2018-12-06_19-15-37

### CODE REVIEW

**Comment by hv14** [comment]
I think the number of users should be the number currently at the event. But I may be wrong

**Comment by divy4** [comment]
Our TA once said that the number of people coming to the event is more helpful, because if you want to know how many people are there, you can just look up from your phone. But if you're feeling a bit nervous about how many people are coming, you can't count that without the app.

**Comment by schmidtwmark** [comment]
It should show the meetup location as well! Look at how it's done in the Review Activity

**Comment by schmidtwmark** [comment]
That's the icon for the current location. You need to make that the icon for the meetup, and have the icon for the user's current location.

**Comment by divy4** [comment]
I agree with mark, good for consistency.

**Comment by nicknytko** [comment]
Ah okay my bad, didn't know the icons had different markers.  I'll fix that.

**Comment by nicknytko** [comment]
photo_2018-12-07_18-18-20

**Pull request merged**
