### PR TITLE
Edit overall app design

### PR DESCRIPTION
**Pull request by ikafrulbasha**
========== new design =============
screen shot 2018-11-27 at 5 10 35 pm
screen shot 2018-11-27 at 5 10 51 pm
screen shot 2018-11-27 at 5 11 08 pm
screen shot 2018-11-27 at 5 11 25 pm
screen shot 2018-11-27 at 5 11 41 pm
screen shot 2018-11-27 at 5 12 01 pm
screen shot 2018-11-27 at 5 12 29 pm
screen shot 2018-11-27 at 5 12 43 pm

========== old design =============

screen shot 2018-11-27 at 2 34 09 pm
screen shot 2018-11-27 at 2 34 28 pm
screen shot 2018-11-27 at 2 34 49 pm
screen shot 2018-11-27 at 2 35 19 pm
screen shot 2018-11-27 at 2 35 56 pm
screen shot 2018-11-27 at 2 36 21 pm
screen shot 2018-11-27 at 2 36 44 pm

### CODE REVIEW

**Comment by schmidtwmark** [comment]
Wow, this looks like a lot of work! I've got some general comments:

1. There are a couple of places where text is not white when it probably should be--notably, the select dogs checkboxes/text, and the minutes remaining on the meetup in progress screen. 

2. I'm not really sure how I feel about the yellow buttons--is there a way we can keep the gradient background but use a more default, flat button style? The progress bar on the create screens can also be restylized, then. I would love to see what everybody else thinks on this.

3. A black separator between the map and the meetup in progress part might help to unify them visually.

4. Can we change the default status bar color to something other than green? Make it dark blue so it matches the gradient?

5. The time picker on the CreateMeetupEndTime screen looks out of place with the pink color.

**Comment by divy4** [comment]
This looks great!

**Comment by nicknytko** [comment]
The flat yellow buttons are a nice improvement from before.  Would it be possible to change the red color in the time picker and social level picker to match everything else?

**Comment by schmidtwmark** [comment]
Definitely better, but in my opinion, it could still be improved. We should look at the material design guidelines for color and pick one of the palettes from the bottom of the page: https://material.io/design/color/#color-theme-creation

We should have a main color, of which a light variant can be a background and a dark variant can be used for buttons and navigation bars. Keeping the dark blue would be a good choice! I really don't think the yellow/blue combo works well, just shades of blue would probably look cleaner and distract less from the function of the prototype. 

Obviously this is just my opinion, and I'd love to hear what everybody else thinks.

**Comment by divy4** [comment]
> I'm also not certain, but shouldn't styles by applied on an app level? Would make things easier than having to change the color on all 1000 different buttons each time we want to make a change.

+1 for styles.

**Comment by schmidtwmark** [comment]
Button colors look much better! I still think the gradient background should be removed—a single light blue color would have a better, simpler look in my opinion.

**Comment by Davidw1339** [comment]
> Button colors look much better! I still think the gradient background should be removed—a single light blue color would have a better, simpler look in my opinion

Yea i feel like a simpler background would suit the material design theme more

**Pull request merged**
